// =============================================================================
// Oryn Graphical User Interface (`src/main.rs`)
// =============================================================================
// Main Rust entrypoint for the Oryn desktop application.
//
// This file initializes the Slint GUI window (`AppWindow`), configures the high-quality
// Skia rendering engine (`winit-skia`) for crisp subpixel text anti-aliasing, binds
// event handlers via submodules (`titlebar`, `workspace`), and executes the Slint event loop.

#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

use std::error::Error;

// Include modules generated by slint-build from `.slint` files
slint::include_modules!();

// Declare modular submodules
mod titlebar;
mod workspace;

fn main() -> Result<(), Box<dyn Error>> {
    // -------------------------------------------------------------------------
    // 0. Force High-Quality Skia Graphics Backend for Clear Text Rendering
    // -------------------------------------------------------------------------
    // Setting `SLINT_BACKEND` to `winit-skia` enables Skia's high-performance 2D
    // canvas renderer, delivering sharp subpixel text anti-aliasing and vector clarity.
    std::env::set_var("SLINT_BACKEND", "winit-skia");

    // -------------------------------------------------------------------------
    // 1. Initialize top-level AppWindow instance
    // -------------------------------------------------------------------------
    // Creates the Slint window context defined in `ui/app-window.slint`.
    let ui = AppWindow::new()?;

    // -------------------------------------------------------------------------
    // 2. Wire Titlebar & Workspace Event Callbacks
    // -------------------------------------------------------------------------
    // Delegates window chrome interactions to `titlebar` module.
    titlebar::setup_titlebar_callbacks(&ui);

    // Delegates document management, folder scanning, file loading & dialogs to `workspace` module.
    workspace::setup_workspace_callbacks(&ui);

    // -------------------------------------------------------------------------
    // 3. Run Main Slint UI Event Loop
    // -------------------------------------------------------------------------
    // Starts event processing loop and blocks until the window is closed.
    ui.run()?;

    Ok(())
}
