// =============================================================================
// Oryn Graphical User Interface (`src/main.rs`)
// =============================================================================
// Main Rust entrypoint for the Oryn desktop application.
//
// This file initializes the Slint GUI window (`AppWindow`), configures the high-quality
// Skia rendering engine (`winit-skia`) for crisp subpixel text anti-aliasing, binds
// event handlers via submodules (`titlebar`, `workspace`, `markdown`), registers `Kode Mono`
// as the default monospace font for StyledText `Style::Code` backtick spans, and executes the Slint event loop.

#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

use std::error::Error;

// Include modules generated by slint-build from `.slint` files
slint::include_modules!();

// Declare modular submodules
mod markdown;
mod titlebar;
mod workspace;

/// Configures `Kode Mono` as the primary font for Slint's `GenericFamily::Monospace`,
/// ensuring `StyledText` `Style::Code` (backtick `` `code` `` spans) render natively in `Kode Mono`.
fn setup_monospace_font() {
    use slint::fontique_010::fontique;
    let kode_mono_bytes = include_bytes!("../assets/font/KodeMono/KodeMono-Regular.ttf");
    let blob = fontique::Blob::new(std::sync::Arc::new(kode_mono_bytes.to_vec()));
    let mut collection = slint::fontique_010::shared_collection();
    let fonts = collection.register_fonts(blob, None);
    let family_ids: Vec<_> = fonts.iter().map(|(family_id, _)| *family_id).collect();
    collection.set_generic_families(
        fontique::GenericFamily::Monospace,
        family_ids.into_iter(),
    );
}

fn main() -> Result<(), Box<dyn Error>> {
    // -------------------------------------------------------------------------
    // 0. Force High-Quality Skia Graphics Backend for Clear Text Rendering
    // -------------------------------------------------------------------------
    // Setting `SLINT_BACKEND` to `winit-skia` enables Skia's high-performance 2D
    // canvas renderer, delivering sharp subpixel text anti-aliasing and vector clarity.
    std::env::set_var("SLINT_BACKEND", "winit-skia");

    // -------------------------------------------------------------------------
    // 1. Initialize top-level AppWindow instance
    // -------------------------------------------------------------------------
    // Creates the Slint window context defined in `ui/app-window.slint`.
    let ui = AppWindow::new()?;

    // -------------------------------------------------------------------------
    // 2. Map Monospace Generic Font Family to Kode Mono
    // -------------------------------------------------------------------------
    setup_monospace_font();

    // -------------------------------------------------------------------------
    // 3. Wire Titlebar & Workspace Event Callbacks
    // -------------------------------------------------------------------------
    // Delegates window chrome interactions to `titlebar` module.
    titlebar::setup_titlebar_callbacks(&ui);

    // Delegates document management, folder scanning, file loading & dialogs to `workspace` module.
    workspace::setup_workspace_callbacks(&ui);

    // -------------------------------------------------------------------------
    // 4. Run Main Slint UI Event Loop
    // -------------------------------------------------------------------------
    // Starts event processing loop and blocks until the window is closed.
    ui.run()?;

    Ok(())
}
