import { Button, VerticalBox } from "std-widgets.slint";

export component AppWindow inherits Window {
    title: "Oryn";
    icon: @image-url("../assets/brand/icon.svg");

    in-out property <int> counter: 42;
    callback request-increase-value();
    VerticalBox {
        Text {
            text: "Counter: \{root.counter}";
        }

        Button {
            text: "Increase value";
            clicked => {
                root.request-increase-value();
            }
        }
    }
}
